name = "telegram_bot"
version = "1.0.0"
target = "javascript"

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glen = ">= 2.2.1 and < 3.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
